<!-- $Id$ -->
<?php
	 include "inc/header.inc";
 ?>
<div class="centcolumnpad">
<h2>Highlight:</h2>

<h3>Coronal heating problem</h3>

<p><img align="left" src="/samples/corona/Trace_171_20050908.jpg" width="250" height="200" border="1" vspace="8" hspace="4" ALT="Image: TRACE/NASA; EUV emission of the solar corona above an active region">
The corona of the Sun was observed to be very hot, which is since then rather unexplained.
Large-scale 3D-MHD models can nowadays test whole scenarios for coronal heating theories in computational models.
With the Pencil Code, one such numerical experiment was performed on several German-national and European-international super computers.
To enable this research, efficient massive-parallel communication and file-input/output was implemented in the Pencil Code recently.</p>

<p><img src="/samples/corona/EM-MAG-Pz.png" width="660" height="242" border="0" vspace="8" hspace="4" ALT="EUV emission; photospheric magnetogram with loops field lines; vertical Poynting flux"></p>

<p>We show here a view from top onto the coronal model that features several hot loops with extreme-UV emission in the spectral lines of, e.g., Fe XV (red, left panel), which is generated by million Kelvin hot plasma.
This emission clearly follows, as expected, the magnetic field (lines, middle panel), because the heat conduction is very efficient parallel to the magnetic field lines.
As responsible for the coronal energy input, we could identify the vertical Poynting flux into the corona (blue/red, right panel), that is caused by horizontal shuffling motions by advection of magnetic field lines in the photosphere, where the plasma beta is large and hence the granulation performs the so-called field-line braiding mechanism to inject magnetic energy.
While these magnetic disturbances travel into the corona, they may induce electric currents, which eventually heat the plasma by Ohmic dissipation.</p>

The model is driven by an active regeion magnetogram observed in the photosphere (black/gray/white, middle panel) and reproduces well observations of the corona.
This also explains the coronal energy input and yields to realistic coronal heating, as was shown by these publications:
<ul>
	<li>Bourdin et al. (2013), A&amp;A 555, A123 (<a href="http://adsabs.harvard.edu/abs/2013A%26A...555A.123B">ADS</a>, DOI: <a href="http://dx.doi.org/10.1051/0004-6361/201321185">10.1051/0004-6361/201321185</a>)</li>
	<li>Bourdin et al. (2014), PASJ 66S, 7 (<a href="http://adsabs.harvard.edu/abs/2014PASJ...66S...7B">ADS</a>, DOI: <a href="http://dx.doi.org/10.1093/pasj/psu123">10.1093/pasj/psu123</a>)</li>
	<li>Bourdin et al. (2015), A&amp;A 580, A72 (<a href="http://adsabs.harvard.edu/abs/2015A%26A...580A..72B">ADS</a>, DOI: <a href="http://dx.doi.org/10.1051/0004-6361/201525839">10.1051/0004-6361/201525839</a>)</li>
</ul>

<?php
	include "inc/footer.inc";
 ?>

