<div class="centerdivider"></div>
<div class="centcolumnpad">
<p>Available as open source code on <a href="https://github.com/pencil-code/pencil-code/" target="_top">https://github.com/pencil-code/pencil-code/</a>.
It is being updated after each change in the developer's repository, which can be accessed both through svn and git; see
<a href="https://pencil-code.org/download.php" target="_top">https://pencil-code.org/download.php</a>.</p>
</div>
