<div class="rightcolumn">

<h2>Pencil News</h2>
Recent news item about the Newsletter,
Pencil Code office hours, and the
the Pencil Code Steering Committee:
<a href="/news.php">[more...]</a>

<div class="rightdivider"></div>

<h2>Get Pencil</h2>
There are several ways how to get the code. <a href="/download.php">[more...]</a>

<div class="rightdivider"></div>

<h2>Learn Pencil</h2>
Quick start guide for beginners, samples, manual &amp; <a href="/doc.php">[more...]</a>

</div><!-- End of rightcolumn -->

